docker-image.yml modify

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -43,7 +43,11 @@ jobs:
           
             #Now we have got the access of EC2 and we will start the deploy .
             cd /home/ubuntu/App/DevOps-experience/wordpress &&
-            docker compose -f compose-production.yml down &&
+            if [ -s compose-production.yml ] ; then
+              docker compose -f compose-production.yml down
+            else
+              echo >&2 "compose-production.yml not found in $PWD"
+            fi
             git fetch origin &&
             git reset --hard origin/main
             docker compose -f compose-production.yml up -d --build
